#!/bin/sh

wget "$1" -O /tmp/speech.wav --quiet
ffmpeg -loglevel panic -y -i /tmp/speech.wav -ar 16000 /tmp/speech.flac
curl -H 'Content-Type: audio/x-flac; rate=16000' 'https://www.google.com/speech-api/v1/recognize?xjerr=1&client=chromium&lang=en-US' -F "myfile=@/tmp/speech.flac" -k
